<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\Escaper;
use Magento\Review\Block\Product\View as ProductReview;
use Magento\Theme\Block\Html\Pager;
use Meetanshi\HyvaWerra\ViewModel\Config;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var ProductReview $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var Pager $toolbar */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var Config $viewModelConfig */
$viewModelConfig = $viewModels->require(Config::class);
$configJson = json_decode($viewModelConfig->getJson() ?? '{}', true);
$storeId = $viewModelConfig->getCurrentStoreId();
$themeColor = $configJson[$storeId]['general']['buttons']['background_color'];

$reviewCollection = $block->getReviewsCollection();
$yellowHex = $themeColor;
$greyHex = $themeColor . '4d';
// Note: Setting the collection on the toolbar block applies pagination, so it has to happen before collection loading.
if ($toolbar = $block->getChildBlock('review_list.toolbar')) {
    $toolbar->setCollection($reviewCollection);
}
$reviewCollection->load()->addRateVotes();

$items = $reviewCollection->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$headingTag = $block->getData('heading_tag') ?: 'h3';
$productName = $block->getProduct()->getName();
$itemCount = count($items);
?>
<?php if (count($items)): ?>
    <div
        id="customer-review-list"
        aria-label="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Customer Reviews')) ?>"
        tabindex="-1"
        class="order-2"
        role="group"
    >
        <div class="w-full px-6 py-3">
            <p class="text-[20px] font-RalewayB"><?= /* @noEscape */ $itemCount .' '. __('Reviews for') .' '. $productName; ?> </p>
            <?php foreach ($items as $review): ?>
                <div itemscope itemprop="review" itemtype="http://schema.org/Review"
                    class="border-b pb-4 my-4 border-container last:border-0 last:mb-0">
                   
                    
                    <div class="mb-2">
                        <strong itemprop="author" itemscope itemtype="https://schema.org/Person">
                            <span itemprop="name" class="text-th-primary-darker"><?= /* @noEscape */ $escaper->escapeHtml($review->getNickname()) ?></span>
                        </strong>
                        <time
                            class="text-th-primary-lighter inline-block ml-2"
                            itemprop="datePublished"
                            datetime="<?= /* @noEscape */ $escaper->escapeHtmlAttr($block->formatDate($review->getCreatedAt(), $format)); ?>"
                        >
                            <span class="sr-only">
                                <?= /* @noEscape */ $escaper->escapeHtml(
                                    $block->formatDate(
                                        $review->getCreatedAt(),
                                        $formatLong
                                    )
                                ) ?>
                            </span>
                            <span aria-hidden="true">
                                <?= /* @noEscape */ $escaper->escapeHtml(
                                    $block->formatDate($review->getCreatedAt(), $format)
                                ) ?>
                            </span>
                        </time>
                    </div>
                     <?php if (count($review->getRatingVotes())): ?>
                        <div class="table mb-2">
                            <?php foreach ($review->getRatingVotes() as $vote): ?>
                                <?php
                                $rating = $vote->getPercent();
                                $ratingSteps = 5;
                                $starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
                                $starsEmpty = floor($ratingSteps - $starsFilled);
                                ?>
                            <div class="table-row" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                               
                                <span class="hidden" itemprop="ratingValue"><?= /* @noEscape */ /** @noEscape */ $starsFilled; ?></span>
                                <div
                                    class="flex flex-row gap-2"
                                    role="img"
                                    aria-label="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled, $ratingSteps))?>"
                                >
                                    <?php $i = 0; ?>
                                    <?php while ($i < $starsFilled): ?>
                                         <svg 
                width="20" 
                class="w-[1.2rem] h-[1.2rem]" 
                style="color: <?= /* @noEscape */ /** @noEscape */ $yellowHex ?>" 
                height="20" 
                viewBox="0 0 20 19" 
                xmlns="http://www.w3.org/2000/svg">
                <path d="M10.3099 0.5L12.555 7.40983H19.8205L13.9426 11.6803L16.1878 18.5902L10.3099 14.3197L4.43203 18.5902L6.67717 11.6803L0.799316 7.40983H8.06474L10.3099 0.5Z" fill="<?= /* @noEscape */ /** @noEscape */ $yellowHex ?>"/>
                </svg>



                                       
                                        <?php $i++; ?>
                                    <?php endwhile; ?>
                                    <?php $i = 0; ?>
                                    <?php while ($i < $starsEmpty): ?>

                                         <svg 
                width="20" 
                class="w-[1.2rem] h-[1.2rem]" 
                style="color: <?= /* @noEscape */ /** @noEscape */ $greyHex ?>" 
                height="20" 
                viewBox="0 0 20 19" 
                xmlns="http://www.w3.org/2000/svg">
                <path d="M10.3099 0.5L12.555 7.40983H19.8205L13.9426 11.6803L16.1878 18.5902L10.3099 14.3197L4.43203 18.5902L6.67717 11.6803L0.799316 7.40983H8.06474L10.3099 0.5Z" fill="<?= /* @noEscape */ /** @noEscape */ $greyHex ?>"/>
                </svg>


                                        
                                        <?php $i++; ?>
                                    <?php endwhile; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <div class="" itemprop="description">
                        <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($toolbar): ?>
        <div class="toolbar review-toolbar mt-4">
            <?= /* @noEscape */ $toolbar->toHtml() ?>
        </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
