<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$textSizeCssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : ' text-3xl';
$titleContainerClasses = $block->getData('maybe_purged_tailwind_section_classes')
    ?? 'container flex flex-col md:flex-row flex-wrap px-0 md:px-auto my-6 font-bold order-2';
$titleHtml = '';
if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $escaper->escapeHtml($block->getPageHeading())
        . '</span>';
}
$actionName = $block->getRequest()->getFullActionName();
$cnt = '';
if ($actionName == 'catalog_product_view') {
    $cnt = "";
} else {
    $cnt = "container";
}
?>
<?php if ($titleHtml): ?>
<div class="<?= /* @noEscape */ $escaper->escapeHtmlAttr($titleContainerClasses . $textSizeCssClass) ?>">
    <h1 class="<?= /* @noEscape */ $cnt ?> md:leading-lh42 text-left w-full text-th-primary-darker font-medium page-title title-font text-[20px] md:text-[30px]"
        <?php if ($block->getId()): ?> id="<?= /* @noEscape */ $escaper->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>>
        <?= /* @noEscape */ $titleHtml ?>
    </h1>
    <?= /* @noEscape */ $block->getChildHtml() ?>
</div>
<?php endif; ?>
