<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SwatchRenderer;
use Magento\Framework\Escaper;
use Magento\Swatches\Block\Product\Renderer\Configurable;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Configurable $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

/** @var SwatchRenderer $swatchRendererViewModel */
$swatchRendererViewModel = $viewModels->require(SwatchRenderer::class);

$product = $block->getProduct();
$productId = $product->getId();

$attributes = $block->decorateArray($block->getAllowAttributes());

$layout = $block->getLayout();
$swatchItemBlock = $layout->getBlock('product.swatch.item');
$swatchItemBlock->setData('product_id', $productId);

$tooltipBlockHtml = $block->getBlockHtml('product.swatch.tooltip');
?>
<?php if ($product->isSaleable() && count($attributes)): ?>
    <script>
        function initConfigurableSwatchOptions_<?= /* @noEscape */ (int) $productId ?>() {
            const configurableOptionsComponent = initConfigurableOptions(
                '<?= /* @noEscape */ (int) $productId ?>',
                <?= /* @noEscape */ $block->getJsonConfig() ?>
            );
            const swatchOptionsComponent = initSwatchOptions(
                <?= /* @noEscape */ $block->getJsonSwatchConfig() ?>
            );

            return Object.assign(
                configurableOptionsComponent,
                swatchOptionsComponent
            );
        }
    </script>

    <div x-data="initConfigurableSwatchOptions_<?= /* @noEscape */ (int) $productId ?>()"
         x-init="initShowSwatchesIntersect();"
         @private-content-loaded.window="onGetCartData($event.detail.data)"
         class="relative mb-4 md:mb-6"
         x-defer="intersect"
    >
        <h2 class="mb-2 md:mb-2 text-xl font-medium text-th-primary-darker title-font">
            <?= /* @noEscape */ $escaper->escapeHtml(__('Product Options:')) ?>
        </h2>
        <div>
            <?php foreach ($attributes as $attribute): ?>
                <?php $attributeId = $attribute->getAttributeId(); ?>
                <?php $productAttribute = $attribute->getProductAttribute();  ?>
                <?php if ($swatchRendererViewModel->isSwatchAttribute($productAttribute)): ?>
                    <div class="items-center flex swatch-attribute border-t first:border-t-0 last:border-b border-container min-h-14
                            swatch-<?= /* @noEscape */ $escaper->escapeHtmlAttr($productAttribute->getAttributeCode()) ?>">
                        <template x-if="showSwatches">
                            <div class="items-center flex flex-col sm:flex-row items-center py-4 sm:py-1 w-full border-gray-300">

                                <label
                                    class="mb-0 w-full sm:w-1/2 text-left text-th-primary-darker label product-option-label"
                                    id="attribute-label-<?= /* @noEscape */ $escaper->escapeHtmlAttr($productId . '-' . $attributeId) ?>"
                                    aria-hidden="true"
                                >
                                    <span><?= /* @noEscape */ $escaper->escapeHtml($productAttribute->getStoreLabel()) ?></span>
                                    <span
                                        class="text-th-primary-darker ml-2 "
                                        x-text="getSwatchText(<?= /* @noEscape */ (int) $attributeId ?>, selectedValues[<?= /* @noEscape */ (int) $attributeId ?>])"
                                    ></span>
                                </label>
                                <div class="w-full sm:ml-2 sm:w-1/2 text-left text-th-primary-darker product-option-values">
                                    <div
                                         class="flex items-center -mx-4 swatch-attribute-options"
                                         role="radiogroup"
                                         aria-label="<?= /* @noEscape */ $escaper->escapeHtmlAttr($productAttribute->getStoreLabel()) ?>"
                                    >
                                        <template
                                            x-for="(item, index) in optionConfig.attributes[<?= /* @noEscape */ (int) $attributeId ?>].options"
                                            :key="item.id"
                                        >
                                            <?= /* @noEscape */ $swatchItemBlock->setData('attribute_id', $attributeId)->toHtml(); ?>
                                        </template>
                                    </div>
                                </div>
                            </div>
                        </template>
                    </div>
                <?php else: ?>
                    <div class="flex items-center flex-col sm:flex-row items-center py-2 w-full border-t border-gray-300 last:border-b">
                        <label class="mb-0 w-full sm:w-1/2 text-left text-th-primary-darker label"
                               for="attribute<?= /* @noEscape */ $escaper->escapeHtmlAttr($attributeId) ?>"
                        >
                            <span>
                                <?= /* @noEscape */ $escaper->escapeHtml($attribute->getProductAttribute()->getStoreLabel()) ?>
                            </span>
                        </label>
                        <div class="w-full sm:ml-2 sm:w-1/2 text-left text-th-primary-darker">
                            <select name="super_attribute[<?= /* @noEscape */ $escaper->escapeHtmlAttr($attribute->getAttributeId()) ?>]"
                                    id="attribute<?= /* @noEscape */ $escaper->escapeHtmlAttr($attributeId) ?>"
                                    class="form-select super-attribute-select max-w-full"
                                    x-on:change="changeOption(<?= /* @noEscape */ (int) $attributeId ?>, event.target.value)"
                                    required>
                                <option value="">
                                    <?= /* @noEscape */ $escaper->escapeHtml(__('Choose an Option...')) ?>
                                </option>
                                <template
                                    x-for="(item, index) in getAllAttributeOptions(<?= /* @noEscape */ (int) $attributeId ?>)"
                                    :key="item.id"
                                >
                                    <option
                                        :value="item.id"
                                        x-html="item.label"
                                        :disabled="!optionIsActive(<?= /* @noEscape */ (int) $attributeId ?>, item.id)"
                                        :selected="selectedValues[<?= /* @noEscape */ $escaper->escapeHtmlAttr($attributeId) ?>] === item.id">
                                    </option>
                                </template>
                            </select>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <?= /* @noEscape */ $tooltipBlockHtml ?>
    </div>

<?php endif;?>

