<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Review\Block\Product\ReviewRenderer;
use Hyva\Theme\Model\ViewModelRegistry;
use Meetanshi\HyvaWerra\ViewModel\Config;

/** @var ReviewRenderer $block */
/** @var Escaper $escaper */
/** @var Config $viewModelConfig */
$viewModelConfig = $viewModels->require(Config::class);
$configJson = json_decode($viewModelConfig->getJson() ?? '{}', true);
$storeId = $viewModelConfig->getCurrentStoreId();
$themeColor = $configJson[$storeId]['general']['buttons']['background_color'];

$rating = $block->getRatingSummary();
$ratingSteps = 5;
$starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
$starFragment = $rating / 100 * $ratingSteps - $starsFilled;
$starsEmpty = floor($ratingSteps - $starsFilled - $starFragment);
$yellowHex = $themeColor;
$greyHex = $themeColor . '4d';
$reviewCount = $block->getReviewsCount();
$productName = $block->getProduct()->getName();
$productId = $block->getProduct()->getId();
$uniqueId = $productId . uniqid();

?>
<?php if ($block->isReviewEnabled() && $reviewCount > 0): ?>
    <div class="block lg:flex mt-1 lg:mt-0 items-center py-2"> 
    <div
        x-data="initRating<?= /* @noEscape */ $uniqueId ?>()"
        x-defer="intersect"
        @keyup.enter="scrollToRatings()"
        @click="scrollToRatings()"
        class="rating-summary flex gap-1 text-left"
        :class="{'cursor-pointer' : reviewsSection}"
        <?php if (!$rating): ?>
            title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Be the first to review this product')) ?>"
        <?php endif; ?>
        :tabindex="reviewsSection ? '0' : '-1'"
        :aria-label="reviewsSection
            ? '<?= /* @noEscape */ $escaper->escapeJs(__('%1 rating. %2 out of %3 stars. Click to go to reviews.', $productName, $starsFilled + $starFragment, $ratingSteps))?>'
            : '<?= /* @noEscape */ $escaper->escapeJs(__('%1 rating. %2 out of %3 stars', $productName, $starsFilled + $starFragment, $ratingSteps))?>'
        "
        :role="reviewsSection ? 'button' : 'img'"
    >
        <?php if ($rating): ?>
            <?php $i = 0; ?>
            <?php while ($i < $starsFilled): ?>
                <svg
                    xmlns="http://www.w3.org/2000/svg" class="fill-current w-[1.2rem] h-[1.2rem]" viewBox="0 0 20 19"
                    style="color: <?= /* @noEscape */ /** @noEscape */ $yellowHex ?>"
                    fill="currentColor"
                    aria-hidden="true"
                >
                    <path d="M10.3099 0.5L12.555 7.40983H19.8205L13.9426 11.6803L16.1878 18.5902L10.3099 14.3197L4.43203 18.5902L6.67717 11.6803L0.799316 7.40983H8.06474L10.3099 0.5Z" fill="<?= /* @noEscape */ /** @noEscape */ $yellowHex ?>"/>
                </svg>
                <?php $i++; ?>
            <?php endwhile; ?>
            <?php if ($starFragment): ?>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 19"
                    fill="currentColor"
                    class="w-[1.2rem] h-[1.2rem]"
                    aria-hidden="true"
                >
                    <defs>
                        <linearGradient id="partialFill<?= /* @noEscape */ $block->getProduct()->getId() ?>">
                            <stop offset="0%" stop-color="<?= /* @noEscape */ /** @noEscape */ $yellowHex ?>"/>
                            <stop offset="<?= /* @noEscape */ $starFragment * 100 ?>%" stop-color="<?= /* @noEscape */ /** @noEscape */ $yellowHex ?>"/>
                            <stop offset="<?= /* @noEscape */ $starFragment * 100 ?>%" stop-color="<?= /* @noEscape */ /** @noEscape */ $greyHex ?>"/>
                            <stop offset="100%" stop-color="<?= /* @noEscape */ /** @noEscape */ $greyHex ?>"/>
                        </linearGradient>
                    </defs>
                    <g fill="url(#partialFill<?= /* @noEscape */ (int)$block->getProduct()->getId() ?>)">
                       <path d="M10.3099 0.5L12.555 7.40983H19.8205L13.9426 11.6803L16.1878 18.5902L10.3099 14.3197L4.43203 18.5902L6.67717 11.6803L0.799316 7.40983H8.06474L10.3099 0.5Z"/>
                    </g>
                </svg>
            <?php endif; ?>
            <?php $i = 0; ?>
                <?php while ($i < $starsEmpty): ?>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="fill-current w-[1.2rem] h-[1.2rem]"
                    style="color: <?= /* @noEscape */ /** @noEscape */ $greyHex ?>"
                    viewBox="0 0 20 19"
                    fill="currentColor"
                    aria-hidden="true"
                >
                    <path d="M10.3099 0.5L12.555 7.40983H19.8205L13.9426 11.6803L16.1878 18.5902L10.3099 14.3197L4.43203 18.5902L6.67717 11.6803L0.799316 7.40983H8.06474L10.3099 0.5Z"/>
                </svg>
                    <?php $i++; ?>
            <?php endwhile; ?>
        <?php else: ?>
            <?php $i = 0; ?>
            <?php while ($i < $ratingSteps): ?>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="fill-current text-gray-200 w-[1.2rem] h-[1.2rem]"
                    viewBox="0 0 20 19"
                    fill="currentColor"
                    aria-hidden="true"
                >
                    <path d="M10.3099 0.5L12.555 7.40983H19.8205L13.9426 11.6803L16.1878 18.5902L10.3099 14.3197L4.43203 18.5902L6.67717 11.6803L0.799316 7.40983H8.06474L10.3099 0.5Z"/>
                </svg>
                <?php $i++; ?>
            <?php endwhile; ?>
        <?php endif; ?>
    </div>
    <div class="review-count lg:ml-2">
        <?php if ($reviewCount > 0) { ?>
            <?= /* @noEscape */  $reviewCount .' '. __('Reviews');?> 
        <?php } ?>
    </div>
</div>
    <script>
        'use strict';

        function initRating<?= /* @noEscape */ $uniqueId ?>() {
            return {
                reviewsSection: document.getElementById('customer-review-list')
                    || document.getElementById('customer-reviews')
                    || document.getElementById('review-form'),
                scrollToRatings() {
                    let scrollTimeout = null

                    if (!this.reviewsSection) {
                        return
                    }

                    addEventListener('scroll', () => {
                        clearTimeout(scrollTimeout);

                        scrollTimeout = setTimeout(() => {
                            if (this.reviewsSection) {
                                this.reviewsSection.focus()
                            }
                        }, 50);
                    }, { once: true });

                    this.reviewsSection.scrollIntoView({behavior: 'smooth'})
                }
            }
        }
    </script>
<?php endif; ?>
