<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductStockItem;
use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;

// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Product $product */
$product = $block->getProduct();

/** @var ProductStockItem $stockItemViewModel */
$stockItemViewModel = $viewModels->require(ProductStockItem::class);
$minSalesQty = $stockItemViewModel->getMinSaleQty($product);
$maxSalesQty = $stockItemViewModel->getMaxSaleQty($product);
$defaultQty = $block->getProductDefaultQty() * 1;

$step = $stockItemViewModel->getQtyIncrements($product)
    ? $stockItemViewModel->getQtyIncrements($product)
    : null;

/**
 * sets minimum and maximum values taking into account the values set in the admin,
 * but taking into account the value of Qty Increments
 */
if ($step) {
    $minSalesQty = ceil($minSalesQty / $step) * $step;
    $maxSalesQty = floor($maxSalesQty / $step) * $step;
    $defaultQty = ceil($defaultQty / $step) * $step;
}

$maxSalesQtyLength = ($maxSalesQty ? strlen((string) $maxSalesQty) : 4)
    + (/* add one if decimal for separator */ (int) $stockItemViewModel->isQtyDecimal($product));


?>
<?php if ($block->shouldRenderQuantity()): ?>
    <script>
        function initQtyField() {

            function findPathParam(key) {
                // get all path pairs after BASE_URL/front_name/action_path/action
                const baseUrl = (BASE_URL.substring(0, 2) === '//' ? 'http:' : '') + BASE_URL;
                const baseUrlParts = (new URL(baseUrl)).pathname.replace(/\/$/, '').split('/');
                const pathParts = window.location.pathname.split('/').slice(baseUrlParts.length + 3);
                for (let i = 0; i < pathParts.length; i += 2) {
                    if (pathParts[i] === key && pathParts.length > i) {
                        return pathParts[i + 1];
                    }
                }
            }

            return {
                qty: <?= /* @noEscape */ /** @noEscape */ $defaultQty ?>,
                itemId: (new URLSearchParams(window.location.search)).get('id') || findPathParam('id'),
                productId: '<?= /* @noEscape */ (int)$product->getId() ?>',
                <?php /* populate the qty when editing a product from the cart */ ?>
                onGetCartData: function onGetCartData(data, $dispatch) {
                    const cart = data && data.data && data.data.cart;
                    if (this.itemId && cart && cart.items) {
                        const cartItem = cart.items.find((item) => {
                            return item.item_id === this.itemId && item.product_id === this.productId;
                        });
                        if (cartItem && cartItem.qty) {
                            this.qty = cartItem.qty;
                            $dispatch('update-qty-' + this.productId, this.qty);
                        }
                    }
                }
            };
        }
    </script>
    <div x-data="initQtyField()" class="btn bg-th-secondary-lighter mt-sticky-qty"
        x-init="$dispatch('update-qty-<?= /* @noEscape */ (int)$product->getId() ?>', qty)"
    >
        <?php if ($product->isSaleable()): ?>
            <div x-data="initQtyField()"
     x-init="$dispatch('update-qty-<?= /* @noEscape */ (int)$product->getId() ?>', qty)"
     class="flex items-center"
>
    <?php if ($product->isSaleable()): ?>
        <label for="qty[<?= /* @noEscape */ (int)$product->getId() ?>]" class="sr-only">
            <?= /* @noEscape */ $escaper->escapeHtml(__('Quantity')) ?>
        </label>

        <!-- Minus Button -->
        <button type="button"
                @click="if (qty > 1) qty--; $dispatch('update-qty-<?= /* @noEscape */ (int)$product->getId() ?>', qty)"
                class="text-[20px] py-1 "
        ><svg width="27" height="26" viewBox="0 0 27 26" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21.5835 13H5.03809" stroke="#666666" stroke-width="1.5"/>
</svg>
</button>

        <!-- Quantity Input -->
        <input name="qty"
               @private-content-loaded.window="onGetCartData($event.detail, $dispatch)"
               id="qty[<?= /* @noEscape */ (int)$product->getId() ?>]"
               form="product_addtocart_form"
               <?php if ($stockItemViewModel->isQtyDecimal($product)): ?>
                   type="text"
                   pattern="[0-9]+(\.[0-9]{1,<?= /* @noEscape */ /** @noEscape */ $maxSalesQtyLength ?>})?"
                   inputmode="decimal"
               <?php else: ?>
                   type="number"
                   pattern="[0-9]{0,<?= /* @noEscape */ /** @noEscape */ $maxSalesQtyLength ?>}"
                   inputmode="numeric"
                   <?php if ($minSalesQty): ?>min="<?= /* @noEscape */ /** @noEscape */ $minSalesQty ?>"<?php endif; ?>
                   <?php if ($maxSalesQty): ?>max="<?= /* @noEscape */ /** @noEscape */ $maxSalesQty ?>"<?php endif; ?>
                   <?php if ($step): ?>step="<?= /* @noEscape */ /** @noEscape */ $step ?>"<?php endif; ?>
               <?php endif; ?>
               :value="qty"
               value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
               class=" py-2 w-20 text-center invalid:ring-2 invalid:ring-red-500"
               x-model.number="qty"
               @input="$dispatch('update-qty-<?= /* @noEscape */ (int)$product->getId() ?>', qty)"
        />

        <!-- Plus Button -->
        <button type="button"
                @click="qty++; $dispatch('update-qty-<?= /* @noEscape */ (int)$product->getId() ?>', qty)"
                class="text-[20px] py-1 "
        ><svg width="27" height="26" viewBox="0 0 27 26" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M13.312 4.72729V21.2727" stroke="#666666" stroke-width="1.5"/>
<path d="M21.5835 13H5.03809" stroke="#666666" stroke-width="1.5"/>
</svg>
</button>
    <?php endif; ?>
</div>

        <?php endif; ?>
    </div>
<?php endif; ?>
