<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="pr-4 lg:w-full">
    <form
        class="form subscribe"
        action="<?= /* @noEscape */ $escaper->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        x-data="initNewsletterForm"
        @submit.prevent="submitForm"
        id="newsletter-validate-detail"
        aria-label="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Join Our Mailing List')) ?>"
    >
        <h2
            class="mb-3 text-[18px] md:text-[25px] tracking-wider tracking-widest text-werra-footerTop-section4-headingColor title-font"
            id="footer-newsletter-heading"
        >
            <?= /* @noEscape */ $escaper->escapeHtml(__('Join Our Mailing List')) ?>
        </h2>
        <div class="flex flex-wrap justify-center gap-2 md:justify-start">
            <label for="newsletter-subscribe" class="sr-only">
                <?= /* @noEscape */ $escaper->escapeHtml(__('Email Address')) ?>
            </label>
            <input
                name="email"
                type="email"    
                required
                id="newsletter-subscribe"
                class="form-input inline-flex w-full border-werra-formElement-footer-default rounded-0 bg-werra-footer-formElement-primary text-werra-footerTop-section4-formElement-textColor"
                placeholder="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Enter your email address')) ?>"
                autocomplete="email"
                aria-describedby="footer-newsletter-heading"
            >
            <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
            <?= /* @noEscape */ $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button class="inline-flex shrink-0 mr-auto xl:mt-0 btn btn-subscribe bg-werra-footer-formElement-btn-primary text-werra-footerTop-section4-formElement-buttonTextColor">
                <?= /* @noEscape */ $escaper->escapeHtml(__('Subscribe')) ?>
            </button>
        </div>
        <div>
            <template x-if="displayErrorMessage">
                <p class="flex items-center text-red">
                    <span class="inline-block w-8 h-8 mr-3">
                        <?= /* @noEscape */ $heroicons->exclamationCircleHtml('', 24, 24, ['aria-hidden' => true]); ?>
                    </span>
                    <template x-for="errorMessage in errorMessages">
                        <span x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>
    </form>
    <div class="w-full">
        <?= /* @noEscape */ $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
    <?= /* @noEscape */  $block->getLayout()
            ->createBlock(\Magento\Cms\Block\Block::class)
            ->setBlockId('footer-social')
            ->toHtml();
    ?>

    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= /* @noEscape */ $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }

        window.addEventListener('alpine:init', () => Alpine.data('initNewsletterForm', initNewsletterForm), {once: true})
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
</div>
