<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Catalog\Block\Product\View\Details;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Details $block */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$divider = $block->getDivider() !== null ? $block->getDivider() : true;
$sectionIsOpen = '';
?>

<div x-data="initProductSections" class="border border-2 rounded-lg">
    <nav
        class="rounded-lg hidden lg:flex pb-6 snap overflow-x-auto overscroll-x-contain"
        aria-label="<?= /* @noEscape */ $escaper->escapeHtml(__('Navigate to Product Section')) ?>"
        x-show="items.length"
    >
        <template x-for="tab in items">
            <button
                type="button"
                class="bg-th-secondary-lighter relative border-b-2 flex-auto py-4 px-3 whitespace-nowrap font-RalewayR
                    aria-expanded:text-th-primary-darker aria-expanded:bg-white
                    after:absolute after:inset-x-0 after:bottom-0 after:border-b-2 after:border-transparent"
                :aria-expanded="sectionItemIsOpen(tab.id)"
                :aria-controls="tab.id"
                @click="openSectionItem(tab.id)"
                x-text="tab.getAttribute('data-name')"
            ></button>
        </template>
    </nav>

    <div
        x-ref="accordion"
        class="px-0 lg:px-8"
        <?php if ($divider): ?>
        class="divide-y lg:divide-y-0 px-4"
        <?php endif; ?>
        style="min-height: 500px"
    >
        <?php
            $productSectionIndex = 0;
        foreach ($block->getGroupSortedChildNames('detailed_info', '') as $sectionName):
            ?>
            <?php
            $sectionBlock = $block->getLayout()->getBlock($sectionName);
            $sectionHtml = (string) $sectionBlock->toHtml();
            $sectionTitle = $sectionBlock->getTitle() ?: $sectionName;
            if ($sectionTitle == 'More Information') {
                $sectionTitle = 'Specifications';
            }
            $sectionId = str_replace('.', '-', $sectionBlock->getNameInLayout());
            if (empty(trim($sectionHtml))) {
                continue;
            }

            if ($productSectionIndex === 0) {
                $sectionIsOpen = $sectionId;
            }
            ?>
            <details
                id="<?= /* @noEscape */ $escaper->escapeHtmlAttr($sectionId) ?>"
                data-name="<?= /* @noEscape */ $escaper->escapeHtml($sectionTitle) ?>"
                x-data="{ id: $el.id }"
                class="group scroll-mt-8 lg:scroll-mt-24"
                :open="sectionItemIsOpen(id)"
            >
                <summary
                    @click.prevent="openSectionItem(id)"
                    class="flex [&::-webkit-details-marker]:hidden px-8 lg:px-0 lg:hidden w-full items-center justify-between py-3 text-lg  group-open:text-th-primary-default"

                >
                    <span><?= /* @noEscape */ $escaper->escapeHtml($sectionTitle) ?></span>
                    <span class="transition-transform group-open:rotate-180">
                    <?= /* @noEscape */ $heroiconsSolid->chevronDownHtml('', 20, 20, ["aria-hidden" => true]); ?>
                    </span>
                </summary>
                <div x-show="sectionItemIsOpen(id)" x-collapse>
                    <div class="pb-3">
                    <?= /* @noEscape */ /** @noEscape  */ $sectionHtml ?>
                    </div>
                </div>
            </details>
            <?php
            $productSectionIndex++;
            endforeach;
        ?>
    </div>
    <script>
        // function initProductSections() {
        //     return {
        //         items: [],
        //         currentOpen: '<?= /* @noEscape */ /** @noEscape */ $sectionIsOpen ?>',
        //         init() {
        //             this.$refs.accordion.style.minHeight = null;
        //             this.items = [...this.$refs.accordion.children];
        //         },
        //         openSectionItem(id) {
        //             this.currentOpen = id;
        //             this.$nextTick(() => {
        //                 document.getElementById(this.currentOpen).scrollIntoView({
        //                     behavior: "smooth",
        //                     block: "nearest",
        //                     inline: "nearest"
        //                 });
        //             });
        //         },
        //         sectionItemIsOpen(id) {
        //             return this.currentOpen === id
        //         },
        //     }
        // }
    </script>
    <script>
    function initProductSections() {
        return {
            items: [],
            currentOpen: '<?= /* @noEscape */ /** @noEscape */ $sectionIsOpen ?>',
            init() {
                this.$refs.accordion.style.minHeight = null;
                this.items = [...this.$refs.accordion.children];
            },
            openSectionItem(id) {
                if (this.currentOpen === id) {
                    this.currentOpen = null; // Close the section if it's already open
                } else {
                    this.currentOpen = id; // Open the new section
                    this.$nextTick(() => {
                        document.getElementById(this.currentOpen).scrollIntoView({
                            behavior: "smooth",
                            block: "nearest",
                            inline: "nearest"
                        });
                    });
                }
            },
            sectionItemIsOpen(id) {
                return this.currentOpen === id;
            },
        }
    }
</script>

    <?php // To ensure the summary is visible when JavaScript is disabled.  ?>
    <noscript>
        <style>details[data-name] summary { display: flex }</style>
    </noscript>
</div>
