<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductAttributes as ProductAttributes;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroiconsOutline */
$heroiconsOutline = $viewModels->require(HeroiconsOutline::class);

/** @var Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}

$productId = $product->getId();

$productAttribute = $viewModels->require(ProductAttributes::class);
$productName = $productAttribute->getValue($product, 'name');

?>

<button x-data="initWishlist()"
        x-defer="intersect"
        @click.prevent="addToWishlist(<?= /* @noEscape */ (int) $productId ?>)"
        aria-label="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
        type="button"
        class="w-[48px] h-[48px] bg-th-secondary-lighter p-0 border-0 inline-flex shrink-0 items-center justify-center text-th-primary-darker hover:text-red-600"
        data-addto="wishlist"
>
    <?= /* @noEscape */ $heroiconsOutline->heartHtml('w-6 h-6', 20, 20, ['aria-hidden' => 'true']) ?>
</button>
