<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$item = $block->getData('item');
$itemUrl = $item['url'] ?? '';


$content = $item['content'] ?? '';

$hasLoadingAttribute = ($block->getImageAttributes() ?: [])['loading'] ?? false;

?>

<?php if ($itemUrl): ?>
<a
    href="<?= /* @noEscape */ $escaper->escapeUrl($itemUrl)?>"
    aria-label="<?= /* @noEscape */ $escaper->escapeHtml(__('Visit %1', ($itemTextLarge ?? $item['image_alt'] || 'page'))) ?>"
    class="block"
>
<?php endif; ?>
    <figure class="relative grid w-full h-[460px] md:h-[580px] lg:h-[800px]">
        <img
            class="absolute inset-0 w-full h-full object-cover" src="<?= /* @noEscape */ $escaper->escapeHtmlAttr($item['image_url']) ?>"
            alt="<?= /* @noEscape */ $escaper->escapeHtmlAttr($item['image_alt'] ?? $item['text_small'] ?? '') ?>"
            width="<?= /* @noEscape */ $escaper->escapeHtmlAttr($item['image_width'] ?? '1280') ?>"
            height="<?= /* @noEscape */ $escaper->escapeHtmlAttr($item['image_height'] ?? '853') ?>"
            <?php if (! $hasLoadingAttribute): ?>
            loading="lazy"
            <?php endif; ?>
            <?php foreach ($block->getImageAttributes() as $name => $value): ?>
                <?= /* @noEscape */ $escaper->escapeHtmlAttr($name) . '="' . $escaper->escapeHtmlAttr($value) . '"' ?>
            <?php endforeach; ?>
        >
        <?php if ($content): ?>
            <div class="container">
                <?= /* @noEscape */ $content; ?>
               
            </div>
        <?php endif; ?>
    </figure>
<?php if ($itemUrl): ?>
</a>
<?php endif; ?>
