<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;

/** @var Image $block */
/** @var Escaper $escaper */

$hasLoadingAttribute = ($block->getCustomAttributes() ?: [])['loading'] ?? false;

?>
<img class="object-contain <?= /* @noEscape */ $escaper->escapeHtmlAttr($block->getClass()) ?>"
     x-data=""
     @update-gallery-<?= /* @noEscape */ (int)$block->getProductId() ?>.window="$root.src = $event.detail"
    <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
        <?= /* @noEscape */ $escaper->escapeHtmlAttr($name) ?>="<?= /* @noEscape */ $escaper->escapeHtmlAttr($value) ?>"
    <?php endforeach; ?>
    src="<?= /* @noEscape */ $escaper->escapeUrl($block->getImageUrl()) ?>"
    <?php if (! $hasLoadingAttribute): ?>
    loading="lazy"
    <?php endif; ?>
    width="<?= /* @noEscape */ $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= /* @noEscape */ $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= /* @noEscape */ $escaper->escapeHtmlAttr($block->getLabel()) ?>"
    title="<?= /* @noEscape */ $escaper->escapeHtmlAttr($block->getLabel()) ?>"
/>
